export default  {
    fileName: state => state.book.fileName,
    menuVisible: state => state.book.menuVisible,
    settingVisible: state => state.book.settingVisible,
    defaultFontSize: state => state.book.defaultFontSize,
    defaultFontFamily: state => state.book.defaultFontFamily,
    fontFamilyVisible: state => state.book.fontFamilyVisible,
    rendition: state => state.book.rendition,
    defaultTheme: state => state.book.defaultTheme,
    progress: state => state.book.progress,
    bookAvailable: state => state.book.bookAvailable,
    book: state => state.book.book,
    section: state => state.book.section,
    cover: state => state.book.cover,
    metaData: state => state.book.metaData,
    navigation: state => state.book.navigation,
    offsetY: state => state.book.offsetY,
    hotSearchOffsetY: state => state.store.hotSearchOffsetY,
    flapCardVisible: state => state.store.flapCardVisible,
    // searchVisible: state => state.store.book.searchVisible,
}
